version: "2"
services:
  zookeeper:
    image: confluent/zookeeper
    container_name: "zookeeper"
    ports:
      - "2181:2181"
    environment:
      zk_id: "1"
  kafka:
    build: docker-kafka
    container_name: "kafka"
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"

networks:
  default:
    external:
      name: segreto